### ISSUE TITLE
Brainstorming: Symfony Bundle

### ISSUE THREAD

**Issue by tacman** [kaermorchen/meiliadmin#53]
I'd like to run this script in my Symfony project, and trying to think of the best way to do it.

I'm wondering if this workflow would be appropriate:

```bash
composer install survos/meiliadmin-bundle
```

Add the default engine and api key
```yaml
survos_meiliadmin:
    host: http://localhost:7700
    api_key: 2u24ksdafjj
```

The adjust the route if necessary, otherwise, open the symfony project project and go to /meiliadmin (or /admin/meili, especially if you have a route rule that block non-admins from that endpoint.

I think this will work, but I wonder in fact if it's the best way.
